### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Stanzilla** [ddavison/sublime-tabs#100]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Benjamin\AppData\Local\atom\app-0.198.0\resources\app.asar\src\atom.js:57:13)
SublimeTabView.initialize (C:\Users\Benjamin\.atom\packages\sublime-tabs\lib\sublime-tab-view.coffee:19:9)
SublimeTabView.View (C:\Users\Benjamin\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\space-pen\lib\space-pen.js:145:25)
SublimeTabView.TabView (C:\Users\Benjamin\.atom\packages\sublime-tabs\lib\tabs\tab-view.coffee:16:44)
```

**Comment by ddavison** [comment]
thanks for reporting this @Stanzilla ! ill add it to the todo list here: #53
