### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Stanzilla** [ddavison/sublime-tabs#104]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\Benjamin\AppData\Local\atom\app-0.198.0\resources\app.asar\exports\atom.js:48:11)
Object.<anonymous> (C:\Users\Benjamin\.atom\packages\sublime-tabs\lib\sublime-tab-bar-view.coffee:1:1)
Object.<anonymous> (C:\Users\Benjamin\.atom\packages\sublime-tabs\lib\sublime-tab-bar-view.coffee:76:4)
Module._compile (module.js:452:26)
```

**Comment by ddavison** [comment]
thanks for reporting this @Stanzilla ! ill add it to the todo list here: #53
