### ISSUE TITLE
Reordering tabs causes Atom to freeze

### ISSUE THREAD

**Issue by Fizzymatt** [ddavison/sublime-tabs#107]
Reordering tabs, by dragging them left or right, causes Atom to freeze.

Uninstalling sublime-tabs seems to fix the issue.

**Comment by ddavison** [comment]
hrmm.  sorry Fizzymatt, I can't seem to reproduce this..  is anybody else able to reproduce?

**Comment by tobyndockerill** [comment]
I'm getting the same problem using version 0.199.0.
Only solution currently is to force-quit the application after attempting to reorder tabs.

**Comment by jayflo** [comment]
I have the same problem with
OS: Windows  SP1
Atom: 0.199.0

**Comment by Fizzymatt** [comment]
Just in case it's any help, here are a few more details of my setup:

OS: OSX Yosemite

Additional Atom packages:
fold-functions (0.2.0)
highlight-selected (0.9.3)
markdown-preview-plus (1.4.0)
project-colorize (0.2.0)
project-manager (1.15.5)
react (0.11.8)
script (2.23.0)
wordcount (2.2.2)

**Comment by davelowensohn** [comment]
I'm having the same problem in Yosemite, it eventually recovers but takes 20+ seconds to resolve.

**Comment by michaelsharpe** [comment]
I am also having this problem.  On OSX Mavericks.  Newest version of atom. Screenshot attached.

![screen shot 2015-05-25 at 4 29 29 pm](https://cloud.githubusercontent.com/assets/2397603/7802018/01b41392-02fc-11e5-9b84-61802b8cf4d7.png)

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
