### ISSUE TITLE
Visual tab order is mangled when opening a file to the right of a temporary tab

### ISSUE THREAD

**Issue by peterjeliot** [ddavison/sublime-tabs#110]
Steps to reproduce:

1. Open three files permanently (this makes seeing the problem more clear)
2. Move to the second tab.
3. Open another file with tree view. It should be open in position 3 of 4.
4. With the recently opened third tab selected, open another file using tree view. This closes the previous temporary tab, while opening a new one, in position 4 of 4.

Result:
The new tab will now occupy the fourth visual tab slot, but when moving through them with cmd-alt-arrows or ctrl-tab/ctrl-shift-tab, the tab is selected as if it were still in the third slot.
This means the tabs look like they're in the order 1234, but logically are in the order 1243.

Tabs should normally be opened in the slot immediately after the current tab, but with this bug they are opened one tab to the right of where they should be.

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
