### ISSUE TITLE
Sublime-tabs doesn't show up in the Install Packages list for Atom v1.0.5

### ISSUE THREAD

**Issue by Maelstrome26** [ddavison/sublime-tabs#133]
Searching for "sublime-tabs" in Atom's package manager doesn't show Sublime Tabs.

Has it been deprecated?

**Comment by Maelstrome26** [comment]
Ahh I just read the other open issue. Maybe somewhere you should state that your package is now part of the core, so people like me don't get confused! :S

**Comment by ddavison** [comment]
Done :)  i was meaning to publish just a new version so the new readme shows up.  I've just published another version, that has the updated readme:

https://atom.io/packages/sublime-tabs

**Comment by Maelstromeous** [comment]
:+1:
