### ISSUE TITLE
[Enhancement] Do not preview direct-opened tabs

### ISSUE THREAD

**Issue by Epigene** [ddavison/sublime-tabs#134]
I enjoy clicking around the tree view and only opening the files in preview tab by enabling the "Use Preview Tabs" option of this package, but it is unfortunate that previewing also affects other opening scenarios.

Specifically:
- Files opened through File->Open
- Files drag-and-dropped
- Files opened through fuzzy search (Command+T)
- Files opened by doubleclicking projectwide search result lines

I would like for files opened by these methods to open in _permanent_ tabs.
Naturally, selectable options regarding the behavior of each of these cases would be best.

**Comment by ddavison** [comment]
hey @Epigene , thanks for this - though this should be migrated to https://github.com/atom/tabs/issues.

:)

**Comment by ddavison** [comment]
closing as i migrated it for you.
