### ISSUE TITLE
Switching to previous/next tab does not always work as expected

### ISSUE THREAD

**Issue by igreg** [ddavison/sublime-tabs#32]
I haven't found a reliable way to reproduce it yet but it has happened to me several times so I'm pretty sure there is a bug somewhere.

So `at some point` going to the previous or next tab (using the keyboard shortcuts) is no longer switching to the tab on the left or right of the current tab and instead jumps to a completely different tab.

Hope this describes accurately the behaviour I'm seeing sometimes.
Let me know if you have any idea of what the problem might be, that might help me to make it reproducible.

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
