### ISSUE TITLE
Does not work with danielmahon/atom-open-last-project

### ISSUE THREAD

**Issue by garrows** [ddavison/sublime-tabs#39]
I like what you were trying to do but I love https://github.com/danielmahon/atom-open-last-project better and sublime-tabs just all the tabs that atom-last-project opens.

**Comment by ddavison** [comment]
@garrows , did you give up on sublime-tabs? :cry:   are you experiencing this issue still?

**Comment by garrows** [comment]
Sorry but I did give up on it. I wasn't too sold on the feature in sublime
anyway. Best of luck though.

**Comment by ddavison** [comment]
Leave a comment
