### ISSUE TITLE
Deprecate in favor of adding to Atom directly

### ISSUE THREAD

**Issue by jmeas** [ddavison/sublime-tabs#43]
This is both an awesome library and feature. But it'd be even better if it made it into Atom proper. There's an open issue about it [over here](https://github.com/atom/tree-view/issues/3) if anyone wants to take a stab at it.

Actually, someone even began work on [a functioning prototype](https://github.com/atom/atom/pull/2205) that seemed to work well, other than a few edge cases. That PR was closed because he ran out of time to keep working on it. That'd be a great place to start from if anyone wanted to take a stab at implementing this.

I'd love to see this land in Atom, but I don't have the time to work on it right now. I just thought this would be a good place to leave a note for anyone looking to work on making it more than a plugin.

@ddavison, would you have any interest in working on it as a core feature of atom?

**Comment by brkattk** [comment]
Anything I can do to help? You name it :)

**Comment by ddavison** [comment]
hey @brkattk , thanks for the offer!  

In order for this to happen, I think the best option for this would be to get this merge done with @ahuth.  

I'm a little busy at the moment, but since you so kindly offered assistance :smiley: - would you be so kind to read the sublime tabs tests and enumerate all of the functionality that sublime tab offers, an example:

[ ] Previews the tab when single click of file
[ ] Opens the tab permanently with double click of file
[ ] ...

This would help me greatly with the merge, so we can make sure that these are complete before merging with ahuth/preview-tabs

Thanks @brkattk !!!

**Comment by erkattak** [comment]
Not sure if this is what you mean, but here it is:
- [x] SublimeTabs Initialization should deactivate and disable the tabs and tree-view package
- [x] Opening a new tab adds a temp class when opening a file
- [x] Opening a new tab when there is an temp tab already will replace an existing temporary tab
- [x] Opening a new tab when there is an temp tab already makes the tab permanent when dbl clicking the tab
- [x] Opening views that do not contain an editor creates a permanent tab
- [x] Opening views that do not contain an editor replaces an existing temp tab
- [x] Opening images should create a temporary tab
- [x] Saving a file should make a tab permanent
- [x] Double clicking a file in the tree view should open a permanent tab in the editor, unless it's not an editable file type
- [x] Single clicking a file in the tree view should open a temporary tab in the editor

**Comment by brkattk** [comment]
Cleaned up prev comment

**Comment by ddavison** [comment]
perfect, thanks! :)

**Comment by ddavison** [comment]
So, ahuth decided to stop development on preview-tabs.  This issue will still remain open as the end-goal would definitely be put into core if we could find a contributor that has enough time to put it in.

**Comment by carlosingles** [comment]
I believe I've implemented this functionality in my [fork](https://github.com/carlosingles/tabs).

I have also submitted a [pull request](https://github.com/atom/tabs/pull/145) to the core tabs package

**Comment by ddavison** [comment]
i'm paying attention to it @carlosingles :+1: :smiley:

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)

Thanks so much @carlosingles .. you're awesome :+1:
