### ISSUE TITLE
Doesn't show file-icon icons on tabs because of missing data- attr

### ISSUE THREAD

**Issue by paradox460** [ddavison/sublime-tabs#47]
[file-icon](https://github.com/DanBrooker/file-icons) icons don't show up on tabs, because the `.title` element of each tab is missing the required `data-name` attribute, which contains the file name.

**Comment by joseph-turner** [comment]
+1

**Comment by roman01la** [comment]
+1

**Comment by Santinell** [comment]
+1

**Comment by njoannidi** [comment]
+1

**Comment by njoannidi** [comment]
Created pull request for this:
https://github.com/ddavison/sublime-tabs/pull/87

**Comment by ddavison** [comment]
Thanks @njoannidi :)
