### ISSUE TITLE
Markdown preview always opens new tab

### ISSUE THREAD

**Issue by iluu** [ddavison/sublime-tabs#48]
It would be cool to have a possibility to keep the same tab displaying markdown preview as well. To be more precise one tab displaying source and one tab displaying preview.

Now when I switch to a new file the source is displayed in a single tab as expected, but markdown preview will always open another new tab.

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
