### ISSUE TITLE
Files opened by Open or Find File commands also go in same tab

### ISSUE THREAD

**Issue by alvinchow86** [ddavison/sublime-tabs#5]
The tree view behavior is exactly what I've been looking for, good work! But the same thing happens for files opened in other ways, namely File->Open, or Find->Find File (Cmd+T or Cmd+P), which may or not be desirable. I would prefer for new tabs to be opened in that case, as Sublime does

**Comment by natesholland** [comment]
I would love to see this happen as well :+1:

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
