### ISSUE TITLE
Problems with atom.workspaceView and more

### ISSUE THREAD

**Issue by simon96aic** [ddavison/sublime-tabs#53]
<b>Deprecated selectors</b>
sublime-tabs
menus\sublime-tree-view.cson
Use the `atom-pane` tag instead of the `pane` class.
keymaps\sublime-tabs.cson
Use the `atom-text-editor` tag instead of the `editor` class.
Use the selector `atom-text-editor[mini]` to select mini-editors.

AND

<b>Deprecated calls</b>
sublime-tabs (13 deprecations)
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 3 timesCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
SublimeTabView.initialize - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tab-view.coffee:19:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:21:29
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
SublimeTabBarView.initialize - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tab-bar-view.coffee:21:20
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
<unknown> - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:29:11
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:35:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:36:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:38:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:39:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:40:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:41:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:42:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:43:9
atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use atom.views.getView(atom.workspace), which returns an HTMLElement.
Called 1 timeCreate Issue on sublime-tabs repo
Atom.Object.defineProperty.get - c:\Users\xxx\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11
Object.activate - c:\Users\xxx\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:37:9

**Comment by Glutnix** [comment]
anyone working on this?

**Comment by ddavison** [comment]
that'd be awesome! no, no one at the moment

**Comment by Glutnix** [comment]
@ddavison Are you on an IRC or something? I might need help getting set up, as this would be my first try at working on an Atom package. Not yet, but maybe soon. Knowing I can ask someone for help will be nice.

**Comment by Glutnix** [comment]
I've tried, and had minor success, but had problems with requiring `atom-space-pen-views` in tabs/tab-bar-view.coffee for some reason. I'm stumped for now.

**Comment by ddavison** [comment]
sure, #sublime-tabs

**Comment by ddavison** [comment]
Apparently Atom will be taking out these deprecated Apis making sublime tabs unusable in a month unless we can fix this. 

 http://blog.atom.io/2015/05/01/removing-deprecated-apis.html

**Comment by Stanzilla** [comment]
Two weeks left! http://blog.atom.io/2015/05/01/removing-deprecated-apis.html

**Comment by ghostlurker** [comment]
I'm hoping you guys will get this working soon.  This is an awesome plugin and I know quite a few folks who use it.

**Comment by ghostlurker** [comment]
And thanks for all the work you've put in on it so far!

**Comment by ddavison** [comment]
it was such a fun project! i hope that https://github.com/atom/tabs/pull/145 makes it in!

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)

thanks everyone for helping out!
