### ISSUE TITLE
Directories are not at top of tree-view after updating Atom

### ISSUE THREAD

**Issue by ezekg** [ddavison/sublime-tabs#60]
This probably has something to do with this issue: https://github.com/atom/tree-view/issues/352. After the update, everything is sorted alphebetically, regardless of type. Disabling the plugin and re-enabling tree-view fixes the issue (since it allows you to check that new setting). Without disabling sublime-tabs, the new setting for tree-view doesn't appear.

**Comment by alekbarszczewski** [comment]
:+1: same here

**Comment by aioue** [comment]
Just enabling tree-view package causes the sort to switch back to folders first.

**Comment by ezekg** [comment]
True, but then tabs quit working until you disable tree-view.

**Comment by Knovour** [comment]
Tree-view need to enable every time when open a new project.

If enable tree-view, when you want to delete a file in project, it will ask you twice with different files

**Comment by aioue** [comment]
Confirmed. Enabling and disabling tree-view after setting the folders first option fixes the issues until the application is closed.

**Comment by CentaurWarchief** [comment]
Same.

**Comment by ddavison** [comment]
I'm not experiencing this behavior, does somebody know what to do to fix this issue? I'm just not able to reproduce

**Comment by CentaurWarchief** [comment]
@ddavison Which version of atom you're using? I'm facing this bug on `0.179`.

**Comment by ddavison** [comment]
disregard!  had to close it and reopen the window

**Comment by CentaurWarchief** [comment]
I had to disable it until there's a fix :(.

Well, you can reproduce it now?

**Comment by ddavison** [comment]
I can reproduce now, yep!

**Comment by ddavison** [comment]
released!  `sublime-tabs@v0.4.9`
