### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ConnorVG** [ddavison/sublime-tabs#66]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
SublimeTabView.initialize (/Users/connor/.atom/packages/sublime-tabs/lib/sublime-tab-view.coffee:19:9)
```

Sorry - the yellow triangle is really annoying me :stuck_out_tongue:

**Comment by ddavison** [comment]
@ConnorVG would you be willing to fix these deprecations since it's "really annoying you"?  ;)

**Comment by ConnorVG** [comment]
Please - https://github.com/ddavison/sublime-tabs/pull/67
