### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by matmuchrapna** [ddavison/sublime-tabs#68]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
atom-workspace.<anonymous> (/Users/vladimir/.atom/packages/sublime-tabs/lib/sublime-tab-bar-view.coffee:22:17)
```

PS. Also there are 14 other deprecated calls

**Comment by ddavison** [comment]
Thanks for this @matmuchrapna , #53 points out the same thing but I just hadn't gotten to it yet :cry:

**Comment by ddavison** [comment]
would you be willing to take a stab at it?

**Comment by matmuchrapna** [comment]
Nope, I would not. Thank you for this awesome plugin, but I have not a lot of time currently, sorry.

**Comment by matmuchrapna** [comment]
As far as it is a duplicate, we can close this issue

**Comment by ddavison** [comment]
i'm glad it's of use to you :)  and no worries.. thanks for closing.

**Comment by ddavison** [comment]
ты говоришь по-русский?  я увидел что ты из Росси?)

**Comment by matmuchrapna** [comment]
говорю по русски, Мы можем поговорить по почте, если хочешь =)

**Comment by ddavison** [comment]
хорошо!  у тебя моя почта?  это на мое сайт  (sorry if there are errors.. still learning ;) )
