### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by Stickiler** [ddavison/sublime-tabs#69]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/share/atom/resources/app/src/atom.js:54:11)
SublimeTabBarView.removeDropTargetClasses (/home/luke/.atom/packages/sublime-tabs/lib/tabs/tab-bar-view.coffee:278:9)
```

**Comment by ddavison** [comment]
Hey @Stickiler , thanks so much for reporting this!  It seems, however, that I already have this issue opened at #53
