### ISSUE TITLE
Tree-view settings

### ISSUE THREAD

**Issue by Fridus** [ddavison/sublime-tabs#75]
`sublime-tabs` panel:
![capture d ecran 2015-03-20 a 14 32 43](https://cloud.githubusercontent.com/assets/3214565/6752384/4de87e96-cf0e-11e4-9419-280c39236ee5.png)

`tree-view` panel:
![capture d ecran 2015-03-20 a 14 33 14](https://cloud.githubusercontent.com/assets/3214565/6752386/50098544-cf0e-11e4-92de-a766227fb0f4.png)

I need `Add Root Folder`.

**Comment by ddavison** [comment]
released v0.5.1 :)

**Comment by Fridus** [comment]
Thanks to you ;)
