### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by robinisaksson** [ddavison/sublime-tabs#78]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
SublimeTabBarView.removeDropTargetClasses (/Users/robinisaksson/.atom/packages/sublime-tabs/lib/tabs/tab-bar-view.coffee:279:9)
```

**Comment by ddavison** [comment]
thanks for reporting it though, robinisaksson :)  dupe of #53
