### ISSUE TITLE
Feature: Tabs opened via quick find (cmd-t) should say open

### ISSUE THREAD

**Issue by tvdeyen** [ddavison/sublime-tabs#81]
As in Sublime Text tabs should should stay open if opened via quick find cmd-t.

**Comment by peterjeliot** [comment]
A quick workaround is to hit cmd-save if you want to keep the file open.

If this is implemented, I would want it as an option. I use cmd-t as a way to preview files as well as open them permanently, and thus want the normal behavior.

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
