### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by linielson** [ddavison/sublime-tabs#85]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (C:\Users\Linielson\AppData\Local\atom\app-0.188.0\resources\app\src\atom.js:54:11)
Object.activate (C:\Users\Linielson\.atom\packages\sublime-tabs\lib\sublime-tabs.coffee:40:9)
```

**Comment by ddavison** [comment]
Thanks for opening this @linielson , sorry it took so long to respond, but this is a duplicate of #53
