### ISSUE TITLE
List open files above tree view

### ISSUE THREAD

**Issue by forivall** [ddavison/sublime-tabs#86]
(feature request)
It would be great if you could either get https://github.com/postcasio/tree-view-open-files to work with this package, or re-implement it within this package.

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)

**Comment by forivall** [comment]
Confirmed. tree-view-open-files works (mostly) properly with core preview tabs. (I'll need to submit some bugs or prs there) :+1:
