### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by simon96aic** [ddavison/sublime-tabs#91]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (c:\Users\XXX\AppData\Local\atom\app-0.176.0\resources\app\src\atom.js:53:11)
atom-workspace.<anonymous> (c:\Users\XXX\.atom\packages\sublime-tabs\lib\sublime-tab-bar-view.coffee:22:17)
```

**Comment by ddavison** [comment]
hey simon, you already created #53 and that's the master ticket for all of these deprecation tickets..  thanks for reporting that! (closing as duplicate)

**Comment by simon96aic** [comment]
sorry, I meant that's a different bug
