### ISSUE TITLE
sublime-tabs & preview-tabs 

### ISSUE THREAD

**Issue by nanocreaator** [ddavison/sublime-tabs#96]
The package do not cohabit with the preview-tabs package. Then, or we can have one or another.
Should be nice if we could keep both working properly.
Thanks

**Comment by ddavison** [comment]
according to @ahuth, the preview-tabs package was actually abandoned.  both of them aren't really supposed to be used in tandem since they do the same thing.  If preview-tabs offers you something that sublime-tabs doesn't, you should create a feature request!

**Comment by ahuth** [comment]
preview-tabs is definitely not being developed anymore, so I suggest using sublime-tabs. I'm also not aware of anything that preview-tabs could do that this package cannot.

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
