### ISSUE TITLE
.tar.gz (and probably other archive formats) stay in tab list

### ISSUE THREAD

**Issue by forivall** [ddavison/sublime-tabs#97]
Browsing through a directory with some .tar.gz files, i noticed that atom is able to preview the list of files within them, however, these preview tabs are not viewed temporarily as is expected with use of this package.

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)

**Comment by forivall** [comment]
And it's solved by core! :+1:
