### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by v3ss0n** [ddavison/sublime-tabs#98]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/opt/atom/resources/app.asar/src/atom.js:57:13)
atom-workspace.<anonymous> (/home/v3ss/.atom/packages/sublime-tabs/lib/sublime-tab-bar-view.coffee:22:17)
atom-workspace.handler (/opt/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
atom-workspace.jQuery.event.dispatch (/opt/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
```

**Comment by ddavison** [comment]
Thanks for reporting this @v3ss0n !

We do however have an issue already open for this #53 .

If you want to take a stab, feel free!

*(closing, as duplicate)*
