### ISSUE TITLE
Sometimes , opening files shows up nothing.

### ISSUE THREAD

**Issue by v3ss0n** [ddavison/sublime-tabs#99]
It happens randomly.

When opening exising files , it shows nothing inside buffer (empty).
Disabling and Enabling sublime tabs make it work again.

**Comment by ddavison** [comment]
I still have yet to see this phenomena.  anybody else experience this?

**Comment by ddavison** [comment]
Closing this issue, as sublime-tabs is now in [core](https://github.com/atom/tabs/pull/145)
